// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjwCTbiGyKEJwYG95Qx-qwoDuZadFOer8',
    appId: '1:233847987701:web:bbc5735d35ba4001bc54bc',
    messagingSenderId: '233847987701',
    projectId: 'hakeekatfarmer',
    authDomain: 'hakeekatfarmer.firebaseapp.com',
    storageBucket: 'hakeekatfarmer.appspot.com',
    measurementId: 'G-8XS1C05MZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5sOK4XWHf8YFmi1Oqp1Nsj3GqUvcuHh4',
    appId: '1:233847987701:android:5da30b41793797a4bc54bc',
    messagingSenderId: '233847987701',
    projectId: 'hakeekatfarmer',
    storageBucket: 'hakeekatfarmer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSXjPFLj6TxYBjk8JSmBN1YqBnkO-NHhA',
    appId: '1:233847987701:ios:83e741ea6356789fbc54bc',
    messagingSenderId: '233847987701',
    projectId: 'hakeekatfarmer',
    storageBucket: 'hakeekatfarmer.appspot.com',
    iosBundleId: 'com.hakeekat.farmer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSXjPFLj6TxYBjk8JSmBN1YqBnkO-NHhA',
    appId: '1:233847987701:ios:08938c29323ea84bbc54bc',
    messagingSenderId: '233847987701',
    projectId: 'hakeekatfarmer',
    storageBucket: 'hakeekatfarmer.appspot.com',
    iosBundleId: 'com.example.hakeekatFarmerVersion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjwCTbiGyKEJwYG95Qx-qwoDuZadFOer8',
    appId: '1:233847987701:web:cd48f32559f97cabbc54bc',
    messagingSenderId: '233847987701',
    projectId: 'hakeekatfarmer',
    authDomain: 'hakeekatfarmer.firebaseapp.com',
    storageBucket: 'hakeekatfarmer.appspot.com',
    measurementId: 'G-J42ZHG5XBG',
  );
}
