// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5xGvNdH7uwHSYguAG0Yl2tAXBQ93Nx34',
    appId: '1:671942765975:web:d0fa236892f96f89f5e8d2',
    messagingSenderId: '671942765975',
    projectId: 'hakeekat-naturals',
    authDomain: 'hakeekat-naturals.firebaseapp.com',
    databaseURL: 'https://hakeekat-naturals-default-rtdb.firebaseio.com',
    storageBucket: 'hakeekat-naturals.appspot.com',
    measurementId: 'G-N9BSKMRVC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ5GgRKdxqLl4i3s016886Jn10oTnnNis',
    appId: '1:671942765975:android:340301246d1c43f5f5e8d2',
    messagingSenderId: '671942765975',
    projectId: 'hakeekat-naturals',
    databaseURL: 'https://hakeekat-naturals-default-rtdb.firebaseio.com',
    storageBucket: 'hakeekat-naturals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_z6UP6-F4q8K3bBgCQiv-1PdZAjwWak',
    appId: '1:671942765975:ios:427018d71ddba190f5e8d2',
    messagingSenderId: '671942765975',
    projectId: 'hakeekat-naturals',
    databaseURL: 'https://hakeekat-naturals-default-rtdb.firebaseio.com',
    storageBucket: 'hakeekat-naturals.appspot.com',
    iosClientId: '671942765975-64na1uvnobfuj3cuctsl6dma3dhcqjhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.hakikatAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2_z6UP6-F4q8K3bBgCQiv-1PdZAjwWak',
    appId: '1:671942765975:ios:427018d71ddba190f5e8d2',
    messagingSenderId: '671942765975',
    projectId: 'hakeekat-naturals',
    databaseURL: 'https://hakeekat-naturals-default-rtdb.firebaseio.com',
    storageBucket: 'hakeekat-naturals.appspot.com',
    iosClientId: '671942765975-64na1uvnobfuj3cuctsl6dma3dhcqjhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.hakikatAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5xGvNdH7uwHSYguAG0Yl2tAXBQ93Nx34',
    appId: '1:671942765975:web:42e41bf094b158c5f5e8d2',
    messagingSenderId: '671942765975',
    projectId: 'hakeekat-naturals',
    authDomain: 'hakeekat-naturals.firebaseapp.com',
    databaseURL: 'https://hakeekat-naturals-default-rtdb.firebaseio.com',
    storageBucket: 'hakeekat-naturals.appspot.com',
    measurementId: 'G-G4QDLHFDEF',
  );

}