// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeiqJZQbssR2CslsH5TV6cwoOTjivZLtc',
    appId: '1:331819345556:web:69207baa71bef83f8bb681',
    messagingSenderId: '331819345556',
    projectId: 'hakikat-app-2e038',
    authDomain: 'hakikat-app-2e038.firebaseapp.com',
    storageBucket: 'hakikat-app-2e038.appspot.com',
    measurementId: 'G-1489NV2E6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAknVJR6yu7NkcVU0f4k0JqgtC3xikymOc',
    appId: '1:331819345556:android:66969f4368389cfa8bb681',
    messagingSenderId: '331819345556',
    projectId: 'hakikat-app-2e038',
    storageBucket: 'hakikat-app-2e038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuhuZaYyyoZn9NGgZ7M3chpVqL_Z10V_s',
    appId: '1:331819345556:ios:705e75bb8c2061638bb681',
    messagingSenderId: '331819345556',
    projectId: 'hakikat-app-2e038',
    storageBucket: 'hakikat-app-2e038.appspot.com',
    iosBundleId: 'com.example.hakikatAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuhuZaYyyoZn9NGgZ7M3chpVqL_Z10V_s',
    appId: '1:331819345556:ios:705e75bb8c2061638bb681',
    messagingSenderId: '331819345556',
    projectId: 'hakikat-app-2e038',
    storageBucket: 'hakikat-app-2e038.appspot.com',
    iosBundleId: 'com.example.hakikatAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeiqJZQbssR2CslsH5TV6cwoOTjivZLtc',
    appId: '1:331819345556:web:c034df6455804c238bb681',
    messagingSenderId: '331819345556',
    projectId: 'hakikat-app-2e038',
    authDomain: 'hakikat-app-2e038.firebaseapp.com',
    storageBucket: 'hakikat-app-2e038.appspot.com',
    measurementId: 'G-R3G4HSL0YZ',
  );
}
